import React from "react";
import { AbsoluteFill, Img, staticFile, useCurrentFrame, useVideoConfig, spring, interpolate } from "remotion";
import { LightLeak } from "@remotion/light-leaks";

export const DentalHookSlide: React.FC<{ durationInFrames: number }> = ({ durationInFrames }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Subtle zoom-in effect on the background
  const scale = interpolate(frame, [0, durationInFrames], [1, 1.1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  // Entrance animations for the text
  const titleEntrance = spring({
    frame: frame,
    fps,
    config: { damping: 14, mass: 0.8 },
  });

  const subtitleEntrance = spring({
    frame: frame - 60,
    fps,
    config: { damping: 14, mass: 0.8 },
  });

  return (
    <AbsoluteFill style={{ backgroundColor: "#000" }}>
      {/* Background Image generated by AI */}
      <AbsoluteFill style={{ transform: `scale(${scale})` }}>
        <Img src={staticFile("images/dental_bg.png")} style={{ width: "100%", height: "100%", objectFit: "cover", opacity: 0.5 }} />
      </AbsoluteFill>

      {/* Light Leaks for premium cinematic feel */}
      <AbsoluteFill>
        <LightLeak />
      </AbsoluteFill>

      {/* Gradient overlay for text readability */}
      <AbsoluteFill style={{ background: "linear-gradient(to top, rgba(0,0,0,0.8) 0%, transparent 70%)" }} />

      <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", padding: "80px" }}>
        <h1
          style={{
            fontFamily: "Inter, sans-serif",
            fontWeight: 800,
            fontSize: "80px",
            color: "#ffffff",
            textAlign: "center",
            lineHeight: 1.1,
            marginBottom: "30px",
            transform: `translateY(${(1 - titleEntrance) * 50}px)`,
            opacity: titleEntrance,
            textShadow: "0 4px 12px rgba(0,0,0,0.5)",
          }}
        >
          ¿Horas perdidas en tu<br />
          <span style={{ color: "#00d2ff" }}>clínica dental?</span>
        </h1>

        <p
          style={{
            fontFamily: "Inter, sans-serif",
            fontWeight: 500,
            fontSize: "40px",
            color: "#e2e8f0",
            textAlign: "center",
            transform: `translateY(${(1 - subtitleEntrance) * 30}px)`,
            opacity: subtitleEntrance,
            maxWidth: "800px",
          }}
        >
          Así lo resolvemos con Inteligencia Artificial.
        </p>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
