"use client";

/**
 * HeroCubes — Canvas text sampling + spring physics + individual drag
 *
 * Formation positions are generated by rendering "B S" in Impact font on an
 * offscreen canvas, sampling lit pixels, and converting to world coordinates.
 * No manual coordinate arrays — the font renderer defines the letter shapes.
 */

import { useRef, useCallback, useEffect } from "react";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";

// ── Isometric target (formation mode) ────────────────────────────────────────
const ISO_X = Math.PI / 6;  // 30° — shows all 3 cube faces
const ISO_Y = Math.PI / 4;  // 45°

// ── Canvas text sampling ──────────────────────────────────────────────────────
// Called lazily inside Scene (guaranteed client-side — Canvas never SSR-renders)
function computeFormationData() {
  const W = 280, H = 78;
  const canvas = document.createElement("canvas");
  canvas.width  = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d")!;

  // Impact: system font, ultra-bold, zero loading cost, thick strokes
  ctx.font          = "bold 66px Impact, 'Arial Black', sans-serif";
  ctx.fillStyle     = "#fff";
  ctx.textBaseline  = "middle";
  ctx.textAlign     = "left";
  ctx.fillText("B",  28, H / 2);
  ctx.fillText("S", 158, H / 2);

  const { data } = ctx.getImageData(0, 0, W, H);
  const STEP = 15; // px between samples → typically 28-38 cubes total

  const bsPositions: [number, number, number][] = [];

  for (let py = Math.floor(STEP / 2); py < H; py += STEP) {
    for (let px = Math.floor(STEP / 2); px < W; px += STEP) {
      const alpha = data[(py * W + px) * 4 + 3];
      if (alpha > 120) {
        // Map canvas coords → 3D world  (x: −4.8…+4.8, y: −2.2…+2.2)
        const wx = (px / W - 0.5) * 9.6;
        const wy = -(py / H - 0.5) * 4.4;
        const wz = (((bsPositions.length * 31) % 17) / 17 - 0.5) * 0.5; // deterministic Z
        bsPositions.push([wx, wy, wz]);
      }
    }
  }

  // Float positions: deterministic spiral (no Math.random — stable across renders)
  const N = bsPositions.length;
  const floatPositions = bsPositions.map((_, i): [number, number, number, number, number] => {
    const angle = (i / N) * Math.PI * 4.5 + i * 0.55;
    const r     = 1.2 + (i % 6) * 0.55;
    return [
      r * Math.cos(angle),
      r * Math.sin(angle) * 0.75,
      (((i * 127) % 17) / 17 - 0.5) * 2.0,  // deterministic Z
      0.25 + (i % 8) * 0.16,                  // rotSeed
      (i % 6) * 0.35,                          // floatDelay
    ];
  });

  return { bsPositions, floatPositions, count: N };
}

// Lazy singleton — only computed once, only on client
let _data: ReturnType<typeof computeFormationData> | null = null;
function getData() {
  if (!_data) _data = computeFormationData();
  return _data;
}

// ── Shared GPU resources ──────────────────────────────────────────────────────
const GEO = new THREE.BoxGeometry(0.72, 0.72, 0.72);
const MAT = new THREE.MeshPhysicalMaterial({
  color:       new THREE.Color(0x2299ff),
  metalness:   0.08,
  roughness:   0.03,
  transparent: true,
  opacity:     0.82,
  side:        THREE.DoubleSide,
  depthWrite:  false,
});

// ── Global state ──────────────────────────────────────────────────────────────
const MOUSE_WORLD = new THREE.Vector3(9999, 9999, 0);
const MOUSE_VEL   = new THREE.Vector3();
const _PREV_MOUSE = new THREE.Vector3();
const GRABBED     = { index: -1 };
const FORMATION   = { active: false };

// ── Mouse tracker ─────────────────────────────────────────────────────────────
const _ray   = new THREE.Raycaster();
const _plane = new THREE.Plane(new THREE.Vector3(0, 0, 1), 0);

function MouseTracker() {
  const { camera } = useThree();
  useFrame(({ pointer }, rawDt) => {
    const dt = Math.max(rawDt, 0.001);
    _PREV_MOUSE.copy(MOUSE_WORLD);
    _ray.setFromCamera(pointer, camera);
    _ray.ray.intersectPlane(_plane, MOUSE_WORLD);
    MOUSE_VEL.copy(MOUSE_WORLD).sub(_PREV_MOUSE).divideScalar(dt);
  });
  return null;
}

// ── Formation controller ──────────────────────────────────────────────────────
function FormationController({ forming }: { forming: boolean }) {
  useEffect(() => { FORMATION.active = forming; }, [forming]);
  return null;
}

// ── Single interactive cube ───────────────────────────────────────────────────
function GlassCube({ index }: { index: number }) {
  const mesh = useRef<THREE.Mesh>(null!);
  const DATA = getData();

  const [ox, oy, oz]         = DATA.floatPositions[index];
  const [rotSeed, floatDelay] = [DATA.floatPositions[index][3], DATA.floatPositions[index][4]];

  const p = useRef({
    pos:       new THREE.Vector3(ox, oy, oz),
    vel:       new THREE.Vector3(),
    orig:      new THREE.Vector3(ox, oy, oz),
    floatOrig: new THREE.Vector3(ox, oy, oz),
    bsOrig:    new THREE.Vector3(...DATA.bsPositions[index]),
    rotX:      rotSeed,
    rotY:      rotSeed * 0.8,
    spinX:     0.2  + rotSeed * 0.05,
    spinY:     0.15 + rotSeed * 0.04,
    _tgt:      new THREE.Vector3(),
    _disp:     new THREE.Vector3(),
  }).current;

  useFrame(({ clock }, rawDt) => {
    const dt        = Math.min(rawDt, 0.05);
    const t         = clock.elapsedTime * 0.35 + floatDelay;
    const isGrabbed = GRABBED.index === index;
    const forming   = FORMATION.active;

    // ── Lerp origin between float and letter position ─────────────────────────
    p.orig.lerp(forming ? p.bsOrig : p.floatOrig, forming ? 0.08 : 0.06);

    // ── Position spring ───────────────────────────────────────────────────────
    if (isGrabbed) {
      p.pos.lerp(MOUSE_WORLD, 0.22);
      p.vel.lerp(MOUSE_VEL, 0.25);
      mesh.current.scale.lerp({ x: 1.08, y: 1.08, z: 1.08 } as any, 0.15);
    } else {
      p._tgt.copy(p.orig);
      if (!forming) p._tgt.y += Math.sin(t) * 0.18;

      p._disp.copy(p.pos).sub(p._tgt);
      p.vel.addScaledVector(p._disp, -4.5 * dt);
      p.vel.addScaledVector(p.vel,   -5.5 * dt);
      p.pos.addScaledVector(p.vel, dt);

      mesh.current.scale.lerp({ x: 1.0, y: 1.0, z: 1.0 } as any, 0.15);
    }

    mesh.current.position.copy(p.pos);

    // ── Rotation ──────────────────────────────────────────────────────────────
    const speed   = p.vel.length();
    const grabbed = isGrabbed ? 4.0 : 0.0;

    if (forming && !isGrabbed) {
      // Decay spin, converge to isometric angle → all cubes show same face
      p.spinX *= 0.78;
      p.spinY *= 0.78;
      p.rotX = THREE.MathUtils.lerp(p.rotX, ISO_X, 0.055);
      p.rotY = THREE.MathUtils.lerp(p.rotY, ISO_Y, 0.055);
    } else {
      const tSX = 0.18 + rotSeed * 0.05 + speed * 2.5 + grabbed;
      const tSY = 0.14 + rotSeed * 0.04 + speed * 1.8 + grabbed;
      p.spinX = THREE.MathUtils.lerp(p.spinX, tSX, 0.07);
      p.spinY = THREE.MathUtils.lerp(p.spinY, tSY, 0.07);
      p.rotX += p.spinX * dt;
      p.rotY += p.spinY * dt;
    }

    mesh.current.rotation.x = p.rotX;
    mesh.current.rotation.y = p.rotY;
  });

  const onDown = useCallback((e: { stopPropagation: () => void }) => {
    e.stopPropagation();
    GRABBED.index = index;
    document.body.style.cursor = "grabbing";
  }, [index]);

  const onUp = useCallback(() => {
    if (GRABBED.index === index) {
      GRABBED.index = -1;
      document.body.style.cursor = "grab";
    }
  }, [index]);

  const onEnter = useCallback(() => {
    if (GRABBED.index === -1) document.body.style.cursor = "grab";
  }, []);

  const onLeave = useCallback(() => {
    if (GRABBED.index === -1) document.body.style.cursor = "default";
  }, []);

  return (
    <mesh
      ref={mesh}
      position={[ox, oy, oz]}
      geometry={GEO}
      material={MAT}
      onPointerDown={onDown}
      onPointerUp={onUp}
      onPointerEnter={onEnter}
      onPointerLeave={onLeave}
    />
  );
}

// ── Scene ─────────────────────────────────────────────────────────────────────
function Scene({ forming }: { forming: boolean }) {
  return (
    <>
      <ambientLight intensity={1.6} />
      <directionalLight position={[6, 8, 5]}  intensity={3.5} color="#ffffff" />
      <pointLight      position={[-4,-3, 4]}  intensity={5.0} color="#47c4ff" />
      <pointLight      position={[ 5, 4,-3]}  intensity={4.0} color="#4466ff" />
      <pointLight      position={[ 0, 0, 7]}  intensity={2.0} color="#99ccff" />
      <MouseTracker />
      <FormationController forming={forming} />
      {Array.from({ length: getData().count }, (_, i) => (
        <GlassCube key={i} index={i} />
      ))}
    </>
  );
}

// ── Canvas ────────────────────────────────────────────────────────────────────
export default function HeroCubes({ forming = false }: { forming?: boolean }) {
  const onUp = useCallback(() => {
    GRABBED.index = -1;
    document.body.style.cursor = "default";
  }, []);

  return (
    <Canvas
      camera={{ position: [0, 0, 11], fov: 48 }}
      gl={{
        alpha:           true,
        antialias:       true,
        powerPreference: "high-performance",
        stencil:         false,
      }}
      dpr={1}
      onPointerUp={onUp}
      onPointerLeave={onUp}
      style={{
        background:  "transparent",
        width:       "100%",
        height:      "100%",
        touchAction: "none",
      }}
    >
      <Scene forming={forming} />
    </Canvas>
  );
}
